version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: ./gradle dependencies

      - run: ./gradle build -x test

      - run: ./gradle test --warning-mode=all
