create table PURCHASE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    NFE VARCHAR(255),
    PRICE DECIMAL(15,2) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

create table PURCHASE_BOOK(
	PURCHASE_ID INT NOT NULL,
	BOOK_ID INT NOT NULL,
	FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASE(ID),
	FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID),
	PRIMARY KEY (PURCHASE_ID, BOOK_ID)
);
